version: '3.9'
name: django_htmx_todo
services:
    web:
        image: berglucas/django_htmx_todo:0.1.0
        networks:
            - web_network
        depends_on:
            - db

    db:
        image: postgres:15.3-alpine3.18
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - web_network

volumes:
    db_data:

networks:
    web_network:
